[book]
authors = ["Arthur Paulino, Damiano Testa, Edward Ayers, Evgenia Karunus, Henrik Böving, Jannis Limperg, Siddhartha Gadgil, Siddharth Bhat"]
language = "zh-CN"
multilingual = false
src = "md"
title = "Lean 4 元编程"

[output.html]
git-repository-url = "https://github.com/Lean-zh/mp-lean-zh"
additional-css = ["./assets/pagetoc.css"]
additional-js = [
  "assets/blockPlay.js",
  "assets/filePlay.js",
  "assets/pagetoc.js",
]

# Settings to overwrite the edit button and make it a code execution button.
# edit-url-template = "https://raw.githubusercontent.com/Lean-zh/mp-lean-zh/master/{path}"

# To ensure that the 404 page functions properly.
# site-url = "https://github.com/Lean-zh/mp-lean-zh"