[book]
authors = ["Arthur Paulino, Damiano Testa, Edward Ayers, Evgenia Karunus, Henrik Böving, Jannis Limperg, Siddhartha Gadgil, Siddharth Bhat"]
language = "en"
multilingual = false
src = "md"
title = "Metaprogramming in Lean 4"

[output.html]
git-repository-url = "https://github.com/leanprover-community/lean4-metaprogramming-book"
additional-css = ["./assets/pagetoc.css"]
additional-js = [
  "assets/blockPlay.js",
  "assets/filePlay.js",
  "assets/pagetoc.js",
]

# Settings to overwrite the edit button and make it a code execution button.
edit-url-template = "https://raw.githubusercontent.com/leanprover-community/lean4-metaprogramming-book/master/{path}"

# To ensure that the 404 page functions properly.
site-url = "https://leanprover-community.github.io/lean4-metaprogramming-book/"